services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  library:
    image: blckbrrynvdr/netology-library:v1.0.0
    working_dir: /app
    ports:
      - 3002:3002
    volumes:
      - ./:/app
    environment:
      - PORT=3002
      - URL_DB=mongodb://root:example@mongo:27017/
    command: npm run dev

